### DISCUSSION TITLE
start Water Heater Circulation now for 5 minutes

### DISCUSSION THREAD

**Discussion by mgiesl2s** [signalkraft/mypyllant-component#212] [Ideas]
It would be useful to be able to create a button in the Home Assistant with which the hot water circulation can be started directly for 5 minutes.

Use case: Hot water circulation does not have to run all the time and saves energy (heat loss due to circulation + power consumption of the circulation pump). Shortly before you go to take a shower, you can start the circulation with a button in the Home Assistant or via the W-Land button.

Unfortunately, the time definition via the "myVAILLANT: Set Water Heater Circulation Time Program" service is too complex for templating.

Example of a static definition:
action: mypyllant.set_dhw_circulation_time_program
target: {}
data:
time_program: |
monday: - start_time: 330
end_time: 1260
tuesday: - start_time: 330
end_time: 1260
wednesday: - start_time: 330
end_time: 1260
thursday: - start_time: 330
end_time: 1260
friday: - start_time: 330
end_time: 1260
saturday: - start_time: 450
end_time: 1260
sunday: - start_time: 450
end_time: 1260

Here you would first have to read out the current calendar settings, save them temporarily and add the current time accordingly and then undo them again after 5 minutes have elapsed.
A direct action to implement this in the myvaillant integration would make sense.

**Comment by tmfoe** [comment]
I have done this via the complicated way you described.

See this automation and change where needed.
It works by adding a time window for the circulation pump from now until the next 10 minutes and then resets to the default.
So your circulation pump settings get overwritten to 16:00-16:10 after use (my default). If you need other time windows, you hace to change the automation accordingly.

As you wrote, it is not very elegant, but it works. I am posting this so that anyone who wants to add this feature can do so, even though the calendar settings are hardcoded.

alias: Zirkulationspumpe 10 Minuten
description: >-
  Aktiviert die Zirkulationspumpe für 10 Minuten und setzt dann für alle Tage
  16:00-16:10
triggers:
  - entity_id:
      - input_boolean.zirkulationspumpe_starten
    to: "on"
    trigger: state
actions:
  - target:
      entity_id: timer.zirkulationspumpe_timer
    action: timer.start
    data: {}
  - target:
      entity_id: water_heater.zuhause_domestic_hot_water_0
    data:
      time_program:
        "{{ now().strftime('%A').lower() }}":
          - start_time: "{{ (now().hour * 60 + now().minute) | int }}"
            end_time: >-
              {{ ((now() + timedelta(minutes=10)).hour * 60 + (now() +
              timedelta(minutes=10)).minute) | int }}
    action: mypyllant.set_dhw_circulation_time_program
  - wait_for_trigger:
      - event_type: timer.finished
        event_data:
          entity_id: timer.zirkulationspumpe_timer
        trigger: event
  - target:
      entity_id: water_heater.zuhause_domestic_hot_water_0
    data:
      time_program:
        monday:
          - start_time: 960
            end_time: 970
        tuesday:
          - start_time: 960
            end_time: 970
        wednesday:
          - start_time: 960
            end_time: 970
        thursday:
          - start_time: 960
            end_time: 970
        friday:
          - start_time: 960
            end_time: 970
        saturday:
          - start_time: 960
            end_time: 970
        sunday:
          - start_time: 960
            end_time: 970
    action: mypyllant.set_dhw_circulation_time_program
  - target:
      entity_id: input_boolean.zirkulationspumpe_starten
    action: input_boolean.turn_off
    data: {}
mode: single


You also can add two helpers (if you don't need them, you can remove them from the automation): a timer (gets displayed with a 10 minute countdown), and a boolean (turn on switch).

**Reply by mgiesl2s** [reply]
Thank you very much. Because i am new to home assistant i have some questions.

I have now created two helpers:
Timer: zirkulationspumpe_timer
input_boolean: zirkulationspumpe_starten

Where should i now put your coding?

In an Automation???

Or in an Button that i create in my home dashboard?

Can you please paste the complete yaml coding of your Button or your Automation?

Thanks

**Reply by tmfoe** [reply]
I have posted in a new reply.

**Comment by mgiesl2s** [comment]
@tmfoe can you please paste your yaml code again? I think the yaml code formation / indentation is not correct.

**Comment by tmfoe** [comment]
Sorry for the late answer.

(Step 1 and 2 can also be done in the Helper interface via "Add helper")

Step 1: Set up the Input Boolean
Add the following code to your configuration.yaml:

```yaml
input_boolean:
  zirkulationspumpe_starten:
    name: Start Circulation Pump
    icon: mdi:pump
```
Step 2: Set up the Timer
Add the following code to your configuration.yaml: 

```yaml
timer:
  zirkulationspumpe_timer:
    duration: "00:10:00"
    icon: mdi:timer-outline
```
Step 3: Create the Automation
Create a new automation in Home Assistant with the following code: 

```yaml
alias: Circulation Pump 10 Minutes
description: >-
  Activates the circulation pump for 10 minutes and then sets 16:00-16:10 for all days
triggers:
  - entity_id:
      - input_boolean.zirkulationspumpe_starten
    to: "on"
    trigger: state
actions:
  - target:
      entity_id: timer.zirkulationspumpe_timer
    action: timer.start
    data: {}
  - target:
      entity_id: water_heater.zuhause_domestic_hot_water_0
    data:
      time_program:
        "{{ now().strftime('%A').lower() }}":
          - start_time: "{{ (now().hour * 60 + now().minute) | int }}"
            end_time: >-
              {{ ((now() + timedelta(minutes=10)).hour * 60 + (now() +
              timedelta(minutes=10)).minute) | int }}
    action: mypyllant.set_dhw_circulation_time_program
  - wait_for_trigger:
      - event_type: timer.finished
        event_data:
          entity_id: timer.zirkulationspumpe_timer
        trigger: event
  - target:
      entity_id: water_heater.zuhause_domestic_hot_water_0
    data:
      time_program:
        monday:
          - start_time: 960
            end_time: 970
        tuesday:
          - start_time: 960
            end_time: 970
        wednesday:
          - start_time: 960
            end_time: 970
        thursday:
          - start_time: 960
            end_time: 970
        friday:
          - start_time: 960
            end_time: 970
        saturday:
          - start_time: 960
            end_time: 970
        sunday:
          - start_time: 960
            end_time: 970
    action: mypyllant.set_dhw_circulation_time_program
  - target:
      entity_id: input_boolean.zirkulationspumpe_starten
    action: input_boolean.turn_off
    data: {}
mode: single
```

4. Lovelace Card
Add this to your Lovelace dashboard: 

```yaml
type: entities
entities:
  - entity: input_boolean.zirkulationspumpe_starten
    name: Circulation Pump
    icon: mdi:pump
  - entity: timer.zirkulationspumpe_timer
    name: Remaining Time
```

How it works

-The user activates the circulation pump via the Input Boolean in the Lovelace interface.
-The automation is triggered and starts the 10-minute timer.
-The time program for the circulation pump is set to the next 10 minutes for the current day.
-After the timer expires, the time program is reset to 16:00-16:10 for all days of the week.
-The Input Boolean is automatically turned off.
-If you want to change time schedule that I have, you have to change 960 and 970, which count the minutes after 00:00. So if you want to reset to 13:00 until 13:30 you have to change the numbers to 780 and 810.
