### ISSUE TITLE
Climate control creates an warning

### ISSUE THREAD

**Issue by JavanXD** [signalkraft/mypyllant-component#122]
Warning: 
```log
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Klima ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 09:06:04 (1 occurrences)
Last logged: 09:06:04
Entity None (<class 'custom_components.mypyllant.climate.ZoneClimate'>) implements HVACMode(s): auto, off, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/signalkraft/mypyllant-component/issues
```

My UI component:

```yaml
title: Vaillant Wärmepumpe
type: vertical-stack
cards:
  - type: horizontal-stack
    cards:
      - features:
          - type: water-heater-operation-modes
            style: dropdown
            operation_modes:
              - Manual
              - Day
              - Auto
              - 'Off'
              - Cylinder Boost
          - type: target-temperature
        type: tile
        entity: water_heater.myhome_domestic_hot_water_0
        hide_state: false
        name: Warmwasser
        state_content:
          - operation_mode
          - current_temperature
        vertical: true
      - type: thermostat
        features:
          - style: dropdown
            hvac_modes:
              - auto
              - 'off'
              - heat_cool
            type: climate-hvac-modes
          - type: climate-preset-modes
            style: dropdown
            preset_modes:
              - boost
              - eco
              - none
              - away
              - sleep
        name: Heizung Referenz-Temperatur Speisekammer
        entity: climate.myhome_zone_heizung_circuit_0_climate
        show_current_as_primary: false
```

Screenshot:
<img width="496" alt="image" src="https://github.com/signalkraft/mypyllant-component/assets/4342160/268b6fd6-189f-4f67-9acf-21cb6f34cc50">

My exported test data can be found here: https://github.com/signalkraft/mypyllant-component/issues/119#issuecomment-1970002640
