### ISSUE TITLE
Current power sensor

### ISSUE THREAD

**Issue by WardinT** [signalkraft/mypyllant-component#182]
### Before submitting a new issue

[ x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
[ x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
[ x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Want to integrate my Heatpump in the energy dashboard (Power Flow Plus), for that I need the current power consumption. I see that sensor in code, but not in my installed HA instance.

My heatpump consists of
- aroTHERM Split (VWL 105/5 AS, VWL 127/6 IS)
- sensoNET VR 921

Current power is visible in the Sunny Portal and the SMA app.

I wonder if this is a bug or some misconfiguration on the heatpump side?

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by signalkraft** [comment]
Did you enable the corresponding option?

**Comment by WardinT** [comment]
I did. But there is no sensor visible the dimension of which is Watt, I only see wp_heizung_consumed_electrical_energy_domestic_hot_water and wp_hydraulic_station_consumed_electrical_energy_heating and a few more in Wh.

**Comment by Therkaz** [comment]
I can confirm this issue. The corresponding option is activated, but the entity does not show up (I can see the consumption in the Vaillant App).
My setup: Arotherm Plus 55/6, VR 921

**Comment by Kruemelino** [comment]
I can confirm this issue too. 

- aroTHERM Split (VWL 125/5 AS S2, VWL 127/5 IS)
- sensoNET VR 921

**Comment by ThomasMatthes** [comment]
Also confirmed.

The actual power `[W]` information of the aroTherm and hydraulic station are visible in the MyVaillant App. Corresponding entities (needed for integration in power flow card plus) are missing in HA. 

- aroTHERM plus VWL 75/6 A S2
- VR 940f myVAILLANT connect

Thanks for providing the mypyllant integration, keep up the great work!

**Comment by signalkraft** [comment]
Could one of you please upload [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) with the real time power usage option enabled?

**Comment by ThomasMatthes** [comment]
> Could one of you please upload [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) with the real time power usage option enabled?

Power information is contained in the generated test data (measurement values are valid):

````
  mpc:
    devices:
      - deviceId: [REPLACED]
        currentPower: 6
      - deviceId: [REPLACED]
        currentPower: 3
````

Used config:

![image](https://github.com/signalkraft/mypyllant-component/assets/152748546/fa1dbbc4-d20a-49d2-a699-b621ffafbf60)

**Comment by WardinT** [comment]
mpc:    devices:      - deviceId: ac5011d6fc8435708fc2d0f770d4bb76729f6cab        currentPower: 16      - deviceId: a0c29de2a5e0ce7c3f3130c367d0bf2ca5d99a10        currentPower: 3--Dr. Thomas Wardin • Talweg 2 • 51469 Bergisch Gladbach, GermanyPhone +49 2202 108800 • Fax +49 2202 244401 • Mobile +49 171 2158565
-------- Ursprüngliche Nachricht --------Von: ThomasMatthes ***@***.***> Datum: 04.07.24  23:23  (GMT+01:00) An: signalkraft/mypyllant-component ***@***.***> Cc: WardinT ***@***.***>, Author ***@***.***> Betreff: Re: [signalkraft/mypyllant-component] Current power sensor (Issue #182) 

Could one of you please upload test data with the real time power usage option enabled?

Power information is contained in the generated test data (measurement values are valid):
  mpc:
    devices:
      - deviceId: [REPLACED]
        currentPower: 6
      - deviceId: [REPLACED]
        currentPower: 3

Used config:
image.png (view on web)

**Comment by Kruemelino** [comment]
```yaml
  mpc:
    devices:
      - deviceId: <--> aroTHERM
        currentPower: 14
      - deviceId: <--> hydraulic station
        currentPower: 3
```

<img width="438" alt="image" src="https://github.com/signalkraft/mypyllant-component/assets/4273483/1deb71c9-f015-4967-9a42-0bfaa4330ac3">

**Comment by signalkraft** [comment]
Thanks! So far that looks like what the component expects.

Could you also go to Developer tools > State and search for `mpc`and `current_power` in the attributes column? You should see the same data there in the attributes of the home entity.

**Comment by Kruemelino** [comment]
Hi,

![Screenshot_20240705_084928_Chrome.jpg](https://github.com/signalkraft/mypyllant-component/assets/4273483/a87029a7-64ad-44a2-a2eb-227706e36d34)

**Comment by signalkraft** [comment]
Alright, getting closer - could you attach the full output of the generate test data service? Data is already anonymized, but of course double check that there's nothing private in there please!

**Comment by Kruemelino** [comment]
```yaml

homes:
  - homeName: 40f509957db14b2924bd79e6aa3b873154a93dac
    serialNumber: e73e5e5c04381c1c9ea3ac72c9d41e8ad735fe5f
    systemId: dd571e89b97e64407a11e214bf48379d8274c6d5
    productMetadata:
      productType: VR921
      productionYear: "23"
      productionWeek: "10"
      articleNumber: "0020260962"
    state: CLAIMED
    migrationState: FINISHED
    migrationFinishedAt: "2024-03-22T08:10:56.617207278Z"
    onlineState: ONLINE
    firmware:
      version: 0357.40.35
      connectedToOldIoTPlatform: null
      updateEnabled: true
      updateRequired: false
    nomenclature: VR 921
    cag: false
    countryCode: DE
    productInformation: VR921
    firmwareVersion: 0357.40.35
dd571e89b97e64407a11e214bf48379d8274c6d5:
  control_identifier:
    controlIdentifier: vrc700
  time_zone:
    timeZone: Europe/Berlin
  diagnostic_trouble_codes:
    - serialNumber: 4b1b1e1ed924c8223a1bc17177476a1b7385cf0f
      articleNumber: "0020266797"
      codes: []
    - serialNumber: 133795909fe781773311a2d2b2f2c46c4c248ed3
      articleNumber: "0010021115"
      codes: []
    - serialNumber: e73e5e5c04381c1c9ea3ac72c9d41e8ad735fe5f
      articleNumber: "0020260962"
      codes: []
    - serialNumber: 9d66c54c5cd6426b18d2844eb17c147968c9dae1
      articleNumber: "0010023523"
      codes: []
    - serialNumber: 2806b7b93f1d803e8421c540144b6f539d3adcd5
      articleNumber: "0020184846"
      codes: []
    - serialNumber: a7b921bdbb2de4b578c05b1824ffc204135054d9
      articleNumber: "0010011640"
      codes: []
  connection_status:
    connected: true
  system:
    state:
      system:
        outdoorTemperature: 14.582031
        outdoorTemperatureAverage24h: 15.761719
        systemFlowTemperature: 31.9375
        systemWaterPressure: 1.9
        legionellaProtectionStartWeekday: "OFF"
        energyManagerState: STANDBY
        systemOff: false
      zones:
        - index: 0
          desiredRoomTemperatureSetpointHeating: 21
          desiredRoomTemperatureSetpoint: 21
          currentRoomTemperature: 26.9375
          currentRoomHumidity: 42
          currentSpecialFunction: NONE
      circuits:
        - index: 0
          circuitState: HEATING
          currentCircuitFlowTemperature: 34.75
          heatingCircuitFlowSetpoint: 27.993982
          calculatedEnergyManagerState: HEATING_ACTIVE
      domesticHotWater:
        - index: 255
          currentSpecialFunction: NONE
          currentDomesticHotWaterTemperature: 48
    properties:
      system:
        controllerType: VRC700
        controllerRevision: R6
        systemScheme: 12
        backupHeaterType: CONDENSING
        backupHeaterAllowedFor: DOMESTIC_HOT_WATER_AND_HEATING
        temporaryAllowBackupHeater: DISABLED
        moduleConfigurationVR71: 3
        energyProvidePowerCutBehavior: DISABLE_HEATPUMP
        smartPhotovoltaicBufferOffset: 10
        externalEnergyManagementActivation: false
      zones:
        - index: 0
          isActive: true
          zoneBinding: CENTRAL_CONTROL
          associatedCircuitIndex: 0
      circuits:
        - index: 0
          mixerCircuitTypeExternal: HEATING
          heatingCircuitType: MIXER_CIRCUIT_EXTERNAL
          isCoolingAllowed: false
      domesticHotWater:
        - index: 255
          minSetpoint: 35
          maxSetpoint: 70
    configuration:
      system:
        continuousHeatingStartSetpoint: -26
        alternativePoint: -10
        heatingCircuitBivalencePoint: -2
        domesticHotWaterBivalencePoint: -5
        adaptiveHeatingCurve: false
        domesticHotWaterMaximumLoadingTime: 60
        domesticHotWaterHysteresis: 5
        domesticHotWaterFlowSetpointOffset: 25
        maxFlowSetpointHeatpumpError: 25
        domesticHotWaterMaximumTemperature: 80
        hybridControlStrategy: BIVALENCE_POINT
        paralellTankLoadingAllowed: false
      zones:
        - index: 0
          general:
            name: "ZONE 1    "
            holidayStartDateTime: "2015-01-01T00:00:00Z"
            holidayEndDateTime: "2015-01-01T00:00:00Z"
            holidaySetpoint: 15
          heating:
            operationModeHeating: AUTO
            setBackTemperature: 15
            dayTemperatureHeating: 21
            timeProgramHeating:
              metaInfo:
                minSlotsPerDay: 0
                maxSlotsPerDay: 3
                setpointRequiredPerSlot: false
              monday:
                - startTime: 360
                  endTime: 1320
              tuesday:
                - startTime: 360
                  endTime: 1320
              wednesday:
                - startTime: 360
                  endTime: 1320
              thursday:
                - startTime: 360
                  endTime: 1320
              friday:
                - startTime: 360
                  endTime: 1320
              saturday:
                - startTime: 450
                  endTime: 1410
              sunday:
                - startTime: 450
                  endTime: 1320
      circuits:
        - index: 0
          heatingCurve: 0.6
          heatingFlowTemperatureMinimumSetpoint: 25
          heatingFlowTemperatureMaximumSetpoint: 45
          heatDemandLimitedByOutsideTemperature: 22
          heatingCircuitFlowSetpointExcessOffset: 0
          epsilon: 2
          setbackModeEnabled: true
          roomTemperatureControlMode: NON
      domesticHotWater:
        - index: 255
          operationModeDomesticHotWater: AUTO
          tappingSetpoint: 50
          holidayStartDateTime: "2015-01-01T00:00:00Z"
          holidayEndDateTime: "2015-01-01T00:00:00Z"
          timeProgramDomesticHotWater:
            metaInfo:
              minSlotsPerDay: 0
              maxSlotsPerDay: 3
              setpointRequiredPerSlot: false
            monday:
              - startTime: 300
                endTime: 540
              - startTime: 1020
                endTime: 1380
            tuesday:
              - startTime: 300
                endTime: 540
              - startTime: 1020
                endTime: 1380
            wednesday:
              - startTime: 300
                endTime: 540
              - startTime: 1020
                endTime: 1380
            thursday:
              - startTime: 300
                endTime: 540
              - startTime: 1020
                endTime: 1380
            friday:
              - startTime: 300
                endTime: 540
              - startTime: 1020
                endTime: 1380
            saturday:
              - startTime: 360
                endTime: 1410
            sunday:
              - startTime: 360
                endTime: 1410
          timeProgramCirculationPump:
            metaInfo:
              minSlotsPerDay: 0
              maxSlotsPerDay: 3
              setpointRequiredPerSlot: false
            monday:
              - startTime: 360
                endTime: 1320
            tuesday:
              - startTime: 360
                endTime: 1320
            wednesday:
              - startTime: 360
                endTime: 1320
            thursday:
              - startTime: 360
                endTime: 1320
            friday:
              - startTime: 360
                endTime: 1320
            saturday:
              - startTime: 450
                endTime: 1410
            sunday:
              - startTime: 450
                endTime: 1320
  current_system:
    system_type: HEATPUMP
    has_emf_capable_devices: true
    primary_heat_generator:
      device_uuid: 9db00365eee2d83e7de71cc3ae57b48f264ad069
      ebus_id: HMU01
      spn: 351
      bus_coupler_address: 0
      article_number: "0010021115"
      emfValid: true
      device_serial_number: 133795909fe781773311a2d2b2f2c46c4c248ed3
      device_type: HEATPUMP
      first_data: "2024-03-20T05:54:27Z"
      last_data: "2024-07-04T19:14:50.022Z"
      data:
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2024-03-20T05:54:27Z"
          to: "2024-07-04T19:14:48.553Z"
        - operation_mode: HEATING
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2024-03-20T05:54:27Z"
          to: "2024-07-04T19:14:48.335Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: EARNED_ENVIRONMENT_ENERGY
          calculated: false
          from: "2024-03-20T05:54:27Z"
          to: "2024-07-04T19:14:49.194Z"
        - operation_mode: HEATING
          value_type: EARNED_ENVIRONMENT_ENERGY
          calculated: false
          from: "2024-03-20T05:54:27Z"
          to: "2024-07-04T19:14:48.975Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: HEAT_GENERATED
          calculated: false
          from: "2024-03-22T09:13:12.587Z"
          to: "2024-07-04T19:14:49.85Z"
        - operation_mode: HEATING
          value_type: HEAT_GENERATED
          calculated: false
          from: "2024-03-22T09:13:12.305Z"
          to: "2024-07-04T19:14:49.6Z"
      product_name: aroTHERM
    secondary_heat_generators: []
    electric_backup_heater:
      device_uuid: 10b50df9b77fde51268138549798eb6aaf5cc776
      ebus_id: VWZ01
      spn: 351
      bus_coupler_address: 0
      article_number: "0010023523"
      emfValid: true
      device_serial_number: 9d66c54c5cd6426b18d2844eb17c147968c9dae1
      device_type: ELECTRIC_AUXILIARY_HEATER
      first_data: "2024-03-20T05:54:27Z"
      last_data: "2024-07-04T18:42:20.06Z"
      data:
        - operation_mode: HEATING
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2024-03-20T05:54:27Z"
          to: "2024-07-04T18:42:19.404Z"
        - operation_mode: HEATING
          value_type: HEAT_GENERATED
          calculated: false
          from: "2024-03-22T09:13:15.853Z"
          to: "2024-07-04T18:42:19.842Z"
      product_name: hydraulic station
    solar_station: null
    ventilation: null
    gateway: null
  mpc:
    devices:
      - deviceId: 9db00365eee2d83e7de71cc3ae57b48f264ad069
        currentPower: 8
      - deviceId: 10b50df9b77fde51268138549798eb6aaf5cc776
        currentPower: 3
  rts:
    statistics:
      - deviceId: 10b50df9b77fde51268138549798eb6aaf5cc776
        operationTime: 0
        onOffCycles: 0
      - deviceId: 9db00365eee2d83e7de71cc3ae57b48f264ad069
        operationTime: 9831
        onOffCycles: 550
  device_buckets:
    startDate: "2024-07-03T00:00:00Z"
    endDate: "2024-07-04T00:00:00Z"
    resolution: HOUR
    operationMode: DOMESTIC_HOT_WATER
    energyType: CONSUMED_ELECTRICAL_ENERGY
    totalConsumption: 418.694424866084
    data:
      - startDate: "2024-07-03T00:00:00Z"
        endDate: "2024-07-03T01:00:00Z"
        value: 0
      - startDate: "2024-07-03T01:00:00Z"
        endDate: "2024-07-03T02:00:00Z"
        value: 0
      - startDate: "2024-07-03T02:00:00Z"
        endDate: "2024-07-03T03:00:00Z"
        value: 0
      - startDate: "2024-07-03T03:00:00Z"
        endDate: "2024-07-03T04:00:00Z"
        value: 0
      - startDate: "2024-07-03T04:00:00Z"
        endDate: "2024-07-03T05:00:00Z"
        value: 89.85517691006484
      - startDate: "2024-07-03T05:00:00Z"
        endDate: "2024-07-03T06:00:00Z"
        value: 328.83924795601916
      - startDate: "2024-07-03T06:00:00Z"
        endDate: "2024-07-03T07:00:00Z"
        value: 0
      - startDate: "2024-07-03T07:00:00Z"
        endDate: "2024-07-03T08:00:00Z"
        value: 0
      - startDate: "2024-07-03T08:00:00Z"
        endDate: "2024-07-03T09:00:00Z"
        value: 0
      - startDate: "2024-07-03T09:00:00Z"
        endDate: "2024-07-03T10:00:00Z"
        value: 0
      - startDate: "2024-07-03T10:00:00Z"
        endDate: "2024-07-03T11:00:00Z"
        value: 0
      - startDate: "2024-07-03T11:00:00Z"
        endDate: "2024-07-03T12:00:00Z"
        value: 0
      - startDate: "2024-07-03T12:00:00Z"
        endDate: "2024-07-03T13:00:00Z"
        value: 0
      - startDate: "2024-07-03T13:00:00Z"
        endDate: "2024-07-03T14:00:00Z"
        value: 0
      - startDate: "2024-07-03T14:00:00Z"
        endDate: "2024-07-03T15:00:00Z"
        value: 0
      - startDate: "2024-07-03T15:00:00Z"
        endDate: "2024-07-03T16:00:00Z"
        value: 0
      - startDate: "2024-07-03T16:00:00Z"
        endDate: "2024-07-03T17:00:00Z"
        value: 0
      - startDate: "2024-07-03T17:00:00Z"
        endDate: "2024-07-03T18:00:00Z"
        value: 0
      - startDate: "2024-07-03T18:00:00Z"
        endDate: "2024-07-03T19:00:00Z"
        value: 0
      - startDate: "2024-07-03T19:00:00Z"
        endDate: "2024-07-03T20:00:00Z"
        value: 0
      - startDate: "2024-07-03T20:00:00Z"
        endDate: "2024-07-03T21:00:00Z"
        value: 0
      - startDate: "2024-07-03T21:00:00Z"
        endDate: "2024-07-03T22:00:00Z"
        value: 0
      - startDate: "2024-07-03T22:00:00Z"
        endDate: "2024-07-03T23:00:00Z"
        value: 0
      - startDate: "2024-07-03T23:00:00Z"
        endDate: "2024-07-04T00:00:00Z"
        value: 0
  rbr:
    rbrCapable: true
  rooms: []
  energy_management:
    energyManager:
      available: false
      compatible: false
    energyManagementStatus:
      thermalStorage:
        domesticHotWater:
          available: false
          selected: false
        heatingBufferCylinder:
          available: false
          selected: true
  ship_self:
    ski: 781fb14a274601457fb631748275abf3f84f5237
    brand: Vaillant
    type: Gateway
    model: VR921
    spineEnabled: false
    spineEnabledStatus: DETERMINED
    spineCapable: true
```
