### ISSUE TITLE
Missing value for consumed electrical energy domestic hot water

### ISSUE THREAD

**Issue by Headkillah** [signalkraft/mypyllant-component#243]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I´ve installed today the latestet release 0.8.22. My setup is VC921 with VCW 20/26CS/1-5 (N-DE) ecoTEC plus. I have 2 HA systems and both of them doesn´t show me the value for the "consumed_electrical_energy_domestic_hot_water" sensor. All other sensor working as expected including the "consumed_electrical_energy_heating" sensor.

In the myVaillaint app the values are showing for the consumed electrical energy.

I don´t have any debug logs because nothing was generated and i don´t have errors. The only problem is as described above.

```
homes:
  - homeName: 93fabfa68b438ee1359b8a880bef872a00bbb687
    serialNumber: 3904f981c0b17320fb98444b7dfe8e90cb0ff8c5
    systemId: 3e2b2edf551a669c49e9444db1fe322a4a9d6813
    productMetadata:
      productType: VR921
      productionYear: "23"
      productionWeek: "19"
      articleNumber: "0020260962"
    state: CLAIMED
    migrationState: FINISHED
    migrationFinishedAt: "2023-08-30T11:35:51.718044051Z"
    onlineState: ONLINE
    firmware:
      version: 0357.40.35
      connectedToOldIoTPlatform: null
      updateEnabled: true
      updateRequired: false
    nomenclature: VR 921
    cag: false
    countryCode: DE
    productInformation: VR921
    firmwareVersion: 0357.40.35
3e2b2edf551a669c49e9444db1fe322a4a9d6813:
  control_identifier:
    controlIdentifier: tli
  time_zone:
    timeZone: Europe/Berlin
  diagnostic_trouble_codes:
    - serialNumber: c43999a24e346cd49f18f2da7f078cf1d61d072e
      articleNumber: "0020274790"
      codes: []
    - serialNumber: 088b45952389c7e0a5c476cb5956d5f3f6735614
      articleNumber: "0020319581"
      codes: []
    - serialNumber: 3904f981c0b17320fb98444b7dfe8e90cb0ff8c5
      articleNumber: "0020260962"
      codes: []
  connection_status:
    connected: true
  system:
    state:
      system:
        outdoorTemperature: 9.0625
        outdoorTemperatureAverage24h: 0
        systemWaterPressure: 1.594
        energyManagerState: HEATING
        systemOff: false
      zones:
        - index: 0
          desiredRoomTemperatureSetpointHeating: 23
          desiredRoomTemperatureSetpoint: 23
          currentSpecialFunction: NONE
          heatingState: IDLE
          quickVetoStartDateTime: "1970-01-01T00:00:00Z"
          quickVetoEndDateTime: "1970-01-01T00:00:00Z"
      circuits:
        - index: 0
          circuitState: HEATING
          heatingCircuitFlowSetpoint: 55.4375
          calculatedEnergyManagerState: HEATING_ACTIVE
      dhw:
        - index: 255
          currentSpecialFunction: REGULAR
          currentDhwTemperature: 47
      ventilation: []
    properties:
      system:
        controllerType: VRC710
        isLegionallaProtectionActivated: "OFF"
        systemScheme: 1
        backupHeaterType: CONDENSING
        backupHeaterAllowedFor: DHW_AND_HEATING
        temporaryAllowBackupHeater: DISABLED
        moduleConfigurationVR71: 3
        energyProvidePowerCutBehavior: DISABLE_HEATPUMP_AND_BACKUP_HEATER
        smartPhotovoltaicBufferOffset: 10
        externalEnergyManagementActivation: false
      zones:
        - index: 0
          isActive: true
          zoneBinding: CENTRAL_CONTROL
          isCoolingAllowed: false
          associatedCircuitIndex: 0
      circuits:
        - index: 0
          mixerCircuitTypeExternal: HEATING
          heatingCircuitType: DIRECT_HEATING_CIRCUIT
      dhw:
        - index: 255
          minSetpoint: 50
          maxSetpoint: 65
      ventilation: []
    configuration:
      system:
        continuousHeatingStartSetpoint: -26
        alternativePoint: -21
        heatingCircuitBivalencePoint: 0
        dhwBivalencePoint: -7
        adaptiveHeatingCurve: false
        dhwMaximumLoadingTime: 60
        dhwHysteresis: 5
        dhwFlowSetpointOffset: 25
        continuousHeatingRoomSetpoint: 20
        hybridControlStrategy: TRIVAI
        maxFlowSetpointHpError: 25
        dhwMaximumTemperature: 80
        maximumPreheatingTime: 0
      zones:
        - index: 0
          general:
            name: Haus
            holidayStartDateTime: "2015-01-01T00:00:00Z"
            holidayEndDateTime: "2015-01-01T00:00:00Z"
            holidaySetpoint: 15
          heating:
            operationModeHeating: TIME_CONTROLLED
            setBackTemperature: 22
            manualModeSetpointHeating: 21
            timeProgramHeating:
              metaInfo:
                minSlotsPerDay: 0
                maxSlotsPerDay: 12
                setpointRequiredPerSlot: true
              monday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
              tuesday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
              wednesday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
              thursday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
              friday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
              saturday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
              sunday:
                - startTime: 0
                  endTime: 330
                  setpoint: 20
                - startTime: 330
                  endTime: 1320
                  setpoint: 23
                - startTime: 1320
                  endTime: 1440
                  setpoint: 20
          cooling: {}
      circuits:
        - index: 0
          heatingCurve: 1.85
          heatingFlowTemperatureMinimumSetpoint: 25
          heatingFlowTemperatureMaximumSetpoint: 90
          heatDemandLimitedByOutsideTemperature: 22
          heatingCircuitFlowSetpointExcessOffset: 0
          setBackModeEnabled: true
          roomTemperatureControlMode: NON
          epsilon: 2
      dhw:
        - index: 255
          operationModeDhw: TIME_CONTROLLED
          tappingSetpoint: 60
          holidayStartDateTime: "2015-01-01T00:00:00Z"
          holidayEndDateTime: "2015-01-01T00:00:00Z"
          timeProgramDhw:
            metaInfo:
              minSlotsPerDay: 0
              maxSlotsPerDay: 3
              setpointRequiredPerSlot: false
            monday:
              - startTime: 330
                endTime: 1350
            tuesday:
              - startTime: 330
                endTime: 1350
            wednesday:
              - startTime: 330
                endTime: 1350
            thursday:
              - startTime: 330
                endTime: 1350
            friday:
              - startTime: 330
                endTime: 1350
            saturday:
              - startTime: 330
                endTime: 1350
            sunday:
              - startTime: 330
                endTime: 1350
          timeProgramCirculationPump:
            metaInfo:
              minSlotsPerDay: 0
              maxSlotsPerDay: 3
              setpointRequiredPerSlot: false
            monday:
              - startTime: 420
                endTime: 1200
            tuesday:
              - startTime: 420
                endTime: 1200
            wednesday:
              - startTime: 420
                endTime: 1200
            thursday:
              - startTime: 420
                endTime: 1200
            friday:
              - startTime: 420
                endTime: 1200
            saturday:
              - startTime: 420
                endTime: 1200
            sunday:
              - startTime: 420
                endTime: 1200
      ventilation: []
  current_system:
    system_type: BOILER_OR_ELECTRIC_HEATER
    has_emf_capable_devices: true
    primary_heat_generator:
      device_uuid: 8010a2619b5ec9b6c255bdf64dd48c272337de90
      ebus_id: BAI00
      spn: 376
      bus_coupler_address: 0
      article_number: "0020319581"
      emfValid: true
      device_serial_number: 088b45952389c7e0a5c476cb5956d5f3f6735614
      device_type: BOILER
      first_data: "2022-06-23T12:47:18Z"
      last_data: "2024-11-29T10:17:37.326Z"
      data:
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2022-06-23T12:47:18Z"
          to: "2024-11-29T10:17:35.92Z"
        - operation_mode: HEATING
          value_type: CONSUMED_ELECTRICAL_ENERGY
          calculated: false
          from: "2022-06-23T12:47:18Z"
          to: "2024-11-29T10:17:35.701Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: CONSUMED_PRIMARY_ENERGY
          calculated: false
          from: "2022-06-23T12:47:18Z"
          to: "2024-11-29T10:17:35.467Z"
        - operation_mode: HEATING
          value_type: CONSUMED_PRIMARY_ENERGY
          calculated: false
          from: "2022-06-23T12:47:18Z"
          to: "2024-11-29T10:17:35.201Z"
        - operation_mode: DOMESTIC_HOT_WATER
          value_type: HEAT_GENERATED
          calculated: false
          from: "2023-08-30T12:40:57Z"
          to: "2024-11-29T10:17:37.326Z"
        - operation_mode: HEATING
          value_type: HEAT_GENERATED
          calculated: false
          from: "2023-08-30T12:40:57Z"
          to: "2024-11-29T10:17:37.108Z"
      product_name: VCW 20/26CS/1-5 (N-DE) ecoTEC plus
    secondary_heat_generators: []
    electric_backup_heater: null
    solar_station: null
    ventilation: null
    gateway: null
  mpc:
    devices: []
  rts:
    statistics:
      - deviceId: 8010a2619b5ec9b6c255bdf64dd48c272337de90
        operationTime: 187423
        onOffCycles: 36453
  device_buckets:
    startDate: "2024-11-28T00:00:00Z"
    endDate: "2024-11-29T00:00:00Z"
    resolution: HOUR
    operationMode: DOMESTIC_HOT_WATER
    energyType: CONSUMED_ELECTRICAL_ENERGY
    totalConsumption: 77.93036484013051
    data:
      - startDate: "2024-11-28T00:00:00Z"
        endDate: "2024-11-28T01:00:00Z"
        value: 0.22697917175889715
      - startDate: "2024-11-28T01:00:00Z"
        endDate: "2024-11-28T02:00:00Z"
        value: 1.931737631990614
      - startDate: "2024-11-28T02:00:00Z"
        endDate: "2024-11-28T03:00:00Z"
        value: 1.931737631990614
      - startDate: "2024-11-28T03:00:00Z"
        endDate: "2024-11-28T04:00:00Z"
        value: 2.966706252129697
      - startDate: "2024-11-28T04:00:00Z"
        endDate: "2024-11-28T05:00:00Z"
        value: 5.4537085902991915
      - startDate: "2024-11-28T05:00:00Z"
        endDate: "2024-11-28T06:00:00Z"
        value: 3.4096445862676057
      - startDate: "2024-11-28T06:00:00Z"
        endDate: "2024-11-28T07:00:00Z"
        value: 1.406507554945055
      - startDate: "2024-11-28T07:00:00Z"
        endDate: "2024-11-28T08:00:00Z"
        value: 3.6148611725737885
      - startDate: "2024-11-28T08:00:00Z"
        endDate: "2024-11-28T09:00:00Z"
        value: 3.3845733470415547
      - startDate: "2024-11-28T09:00:00Z"
        endDate: "2024-11-28T10:00:00Z"
        value: 3.8802064983793687
      - startDate: "2024-11-28T10:00:00Z"
        endDate: "2024-11-28T11:00:00Z"
        value: 0
      - startDate: "2024-11-28T11:00:00Z"
        endDate: "2024-11-28T12:00:00Z"
        value: 2.1121676936619718
      - startDate: "2024-11-28T12:00:00Z"
        endDate: "2024-11-28T13:00:00Z"
        value: 3.265223371478873
      - startDate: "2024-11-28T13:00:00Z"
        endDate: "2024-11-28T14:00:00Z"
        value: 0
      - startDate: "2024-11-28T14:00:00Z"
        endDate: "2024-11-28T15:00:00Z"
        value: 3.403887313275084
      - startDate: "2024-11-28T15:00:00Z"
        endDate: "2024-11-28T16:00:00Z"
        value: 12.050800004997775
      - startDate: "2024-11-28T16:00:00Z"
        endDate: "2024-11-28T17:00:00Z"
        value: 9.5380238060513
      - startDate: "2024-11-28T17:00:00Z"
        endDate: "2024-11-28T18:00:00Z"
        value: 0.2159055897887324
      - startDate: "2024-11-28T18:00:00Z"
        endDate: "2024-11-28T19:00:00Z"
        value: 2.5477071005917162
      - startDate: "2024-11-28T19:00:00Z"
        endDate: "2024-11-28T20:00:00Z"
        value: 2.6383312200619895
      - startDate: "2024-11-28T20:00:00Z"
        endDate: "2024-11-28T21:00:00Z"
        value: 2.7053401564261557
      - startDate: "2024-11-28T21:00:00Z"
        endDate: "2024-11-28T22:00:00Z"
        value: 7.169584584712996
      - startDate: "2024-11-28T22:00:00Z"
        endDate: "2024-11-28T23:00:00Z"
        value: 4.076731561707524
      - startDate: "2024-11-28T23:00:00Z"
        endDate: "2024-11-29T00:00:00Z"
        value: 0
  rbr:
    rbrCapable: true
  rooms: []
  energy_management:
    energyManager:
      available: false
      compatible: false
    energyManagementStatus:
      thermalStorage:
        domesticHotWater:
          available: false
          selected: false
        heatingBufferCylinder:
          available: false
          selected: true
  ship_self:
    ski: 2814f8d6622418f2bc3467b9076f3e3f8126f82d
    brand: Vaillant
    type: Gateway
    model: VR921
    spineEnabled: true
    spineEnabledStatus: DETERMINED
    spineCapable: true
```
