### ISSUE TITLE
Energy consumption of heat pump missing

### ISSUE THREAD

**Issue by sebastianmenzl** [signalkraft/mypyllant-component#296]
### Discussed in https://github.com/signalkraft/mypyllant-component/discussions/295

<div type='discussions-op-text'>

<sup>Originally posted by **sebastianmenzl** February 13, 2025</sup>
Hello, 

since a few weeks the energy information is missing. e.g.
- Consumed Electrical Energy Domestic Hot Water
- Consumed Electrical Energy Heating...

Further discussion about this issue is in the Home Assistant Forum... [Link](https://community.home-assistant.io/t/myvaillant-integration/542610/464)</div>

**Comment by gio-dot** [comment]
I have no longer issues since i setup Energy data retieving every 2 hours (using autmation), so the problem is not in integration but in Vaillant side. Plus this issue was already discussed several times here.

![Image](https://github.com/user-attachments/assets/9a7d726b-8f21-4eb0-95f4-36e4e0385b4a)

**Comment by fkhademi** [comment]
@gio-dot can you please share a screenshot from your settings?  This app was working flawlessly for me until I updated it via HA.  I keep hitting api query quota limits and am looking to get the data query stable again.

<img width="1410" alt="Image" src="https://github.com/user-attachments/assets/07d3a4ef-9752-47bd-8881-07a937e0f163" />

**Comment by Krusty1977** [comment]
Same problem here... I deactivated a lot of entities hoping that this may reduce the number of requests but I still run into the quota limits... A screenshot of parameters which work would be helpful...

**Comment by gio-dot** [comment]
Here it is

![Image](https://github.com/user-attachments/assets/c4b07f50-a960-419f-a78e-5940cdab8310)

```
alias: Vaillant update dati energia
description: Update myVAILLANT energy data
triggers:
  - trigger: time
    at: "00:01:00"
  - trigger: time
    at: "03:00:00"
  - trigger: time
    at: "06:00:00"
  - trigger: time
    at: "09:00:00"
  - trigger: time
    at: "12:00:00"
  - trigger: time
    at: "15:00:00"
  - trigger: time
    at: "18:00:00"
  - trigger: time
    at: "21:00:00"
conditions: []
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - >-
          sensor.seve_device_0_arotherm_consumed_electrical_energy_domestic_hot_water
mode: single
```
