### ISSUE TITLE
Circulation of hot water

### ISSUE THREAD

**Issue by o2-sylog** [signalkraft/mypyllant-component#328]
Hi, thank you for your integration... I would like to ask if it would be possible to implement switching on and off the circulation of hot water?

**Comment by Zbiku91** [comment]
Actually, it is implemented already, but only as the schedule:
https://signalkraft.com/mypyllant-component/2-services/#__tabbed_1_4

So in my implementation I did the phisycal switch in my bathroom, so when I want to take a shower, I push that button -> that triggers the automation that changing the schedule to 24/7, then after 5 minutes it changing it back to the previous state. 

Please be aware, that when you call that service, you have to keep at least one time range for wate circulation (I keep it sunday 13:00-13:10, so the water heater is working anyway)

**Comment by devandi23** [comment]
@Zbiku91 @o2-sylog does this work for you? I only recently added this integration to home assistant and added this service to my automation but when the automation is triggered, I see in the logs that it fails with "Error executing script. Unexpected error for call_service at pos 2: 404, message='Resource Not Found', url='https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/<my_uuid>/domestic-hot-water/255/circulation-pump-time-windows'"

Any ideas how to fix this?

**Comment by Zbiku91** [comment]
Works as automation quite long time... Do other vaillant entities work for you?
Here is the automation code to enable circulation and disable it after some minutes:
```
alias: POMPA Cyrkulacja pompy na 10 min
description: ""
triggers:
  - entity_id:
      - input_boolean.circulation_pump_10_min
    to: "on"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.circulation_pump_10_min
    state: "off"
    enabled: false
actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 49
      color_name: mediumvioletred
    target:
      entity_id: light.esphome_web_f7d3c6_leds_bathroom_shelf
  - data:
      time_program:
        monday:
          - start_time: 0
            end_time: 1430
        tuesday:
          - start_time: 0
            end_time: 1430
        wednesday:
          - start_time: 0
            end_time: 1430
        thursday:
          - start_time: 0
            end_time: 1430
        friday:
          - start_time: 0
            end_time: 1430
        saturday:
          - start_time: 0
            end_time: 1430
        sunday:
          - start_time: 0
            end_time: 1430
    action: mypyllant.set_dhw_circulation_time_program
    target:
      entity_id: water_heater.rzemien_311k_domestic_hot_water_0
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - data:
      time_program:
        sunday:
          - start_time: 780
            end_time: 790
    action: mypyllant.set_dhw_circulation_time_program
    target:
      entity_id: water_heater.rzemien_311k_domestic_hot_water_0
  - metadata: {}
    data: {}
    target:
      entity_id: input_boolean.circulation_pump_10_min
    action: input_boolean.turn_off
  - action: light.turn_off
    metadata: {}
    data:
      transition: 5
    target:
      entity_id: light.esphome_web_f7d3c6_leds_bathroom_shelf
mode: single
```
