### ISSUE TITLE
Setpoint Domestic Hot Water Temperature via Script

### ISSUE THREAD

**Issue by spirit0607** [signalkraft/mypyllant-component#50]
Hey, first of all thank you for this reply great working Adapter! I want to set the Domestic Hot Water Temperature Setpoint via a Script, but I only can Switch Hot Water on / off. How can I **set a Temperature**?

<img width="649" alt="Bildschirmfoto 2023-11-24 um 19 53 11" src="https://github.com/signalkraft/mypyllant-component/assets/69988146/4584c225-421b-4b70-b20e-bb3d22ea4956">

**Comment by signalkraft** [comment]
Home assistant has a built in service called `water_heater.set_temperature` that allows you to set the temperature:

```yaml
service: water_heater.set_temperature
data:
  temperature: 55
target:
  entity_id: water_heater.domestic_hot_water_0
```

**Comment by spirit0607** [comment]
Thank you very much for that quick answer and help! But I'am afraid I need your help again. I tried many different thinks in the last couple of days, but I don't get it. Here is my automations.yaml and my configuration.yaml. 

I want to set the temperature every day at 17:35 to 48 degrees. Maybe you can help me. I appreciate a lot! Thank you!

automations.yaml
```
- id: '1695380354757'
  alias: Wanddisplay on
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 8eab9f9268b7221040dde9da47f3dc53
    entity_id: 789a6bc68598df56c118daa37a485e0c
    domain: binary_sensor
  condition: []
  action:
  - device_id: c7412c2442dcae2bf9e18046dc3bd75e
    domain: mobile_app
    type: notify
    message: An
  mode: single
- id: '1700929984869'
  alias: Wasser wärmer
  description: ''
  trigger:
  - platform: time
    at: '17:35:00'
  condition: []
  action:
  - event: ''
    event_data:
      service: water_heater.set_temperature
      data:
        temperature: 48
      target:
        entity_id: water_heater.domestic_hot_water_0
  mode: single
```
configuration.yaml

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
   - /local/card-mod.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
# Fenster zaehlen
  - platform: template
    sensors:
      offene_fenster:
        value_template: >
          {{ expand('binary_sensor.alle_fenster')
            | selectattr('state', 'eq', 'on')
            | list | count | int }}
binary_sensor:
  - platform: template
    sensors:
      enocean_wohnzimmerfenstergriff_wz:
        unique_id: enocean_wohnzimmerfenstergriff_wz_gekippt
        friendly_name: Wohnzimmertür AZ
        device_class: door
        value_template: "{{ not is_state('sensor.wohnzimmertur_ch_wohnzimmertur', 'closed') }}"
  - platform: template
    sensors:
      enocean_kuchenfenstergriff_wz:
        unique_id: enocean_kuchenfenstergriff_wz_gekippt
        friendly_name: Küchentür AZ
        device_class: door
        value_template: "{{ not is_state('sensor.kuchentur_ch_kuchentur', 'closed') }}"
```
